### ISSUE TITLE
platform specific `gdk_*` bindings are not in the released `gtk4` package

### ISSUE THREAD

**Issue by hasanpasha** [DerryAlex/zig-gir-ffi#23]
`gdk_wayland.zig`, `gdk_x11.zig`, `gdk_macos.zig`, and `gdk_win32.zig` are not present in the package. I could generate it for myself using the instructions in the README file, but it would be good if they were included in the distributed package.

**Comment by DerryAlex** [comment]
Support for wayland, x11 and win32 added

**Comment by hasanpasha** [comment]
Hey I got an issue using these as they are not in the main `gtk` namespace neither in `gdk` namespace, I also tried to import it directly but I got `error: file exists in multiple modules`. I solved the issue for me by importing them into the `gtk` namespace

**Comment by DerryAlex** [comment]
`error: file exists in multiple modules` has been fixed in master. Each file now comes as a module so it would not exist in multiple modules. Platform specific APIs are currently not exposed in "general" namespaces, like `gdk`. You can use `@import("gtk")` together with `@import("gdk_wayland")`.

This might take a while to land. There will be other fixes related to this issue. For example, bring `GLibWin32.gir`.

**Comment by hasanpasha** [comment]
Got it.
